apiVersion: v1
kind: Service
metadata:
  name: booking-app
spec:
  type: NodePort
  selector:
    app: booking-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      containers:
        - name: booking-app
          image: booking-app:1.0.0
          imagePullPolicy: Never
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/booking_db
            - name: DB_USER
              value: booking_user
            - name: DB_PASSWORD
              value: booking_pass
          ports:
            - containerPort: 8080